name: test vagrant

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - run: vagrant up

      - run: vagrant ssh -c "sudo -i -u isucon bin/benchmarker --help"
